// Pull the ABIs the frontend needs out of Foundry's build output.
//
// Generated rather than hand-copied so the UI can never drift from the deployed contracts —
// a stale hand-maintained ABI is a silent source of "why is this call reverting".
//
//   npm run abis      (after `forge build`)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../contracts/out");
const dest = resolve(here, "../src/generated");

const WANTED = {
  SWRVault: "SWRVault.sol/SWRVault.json",
  IkrarAkadNFT: "IkrarAkadNFT.sol/IkrarAkadNFT.json",
  MockIDRX: "MockIDRX.sol/MockIDRX.json",
  MockAggregator: "MockAggregator.sol/MockAggregator.json",
  MockSwapRouter: "MockSwapRouter.sol/MockSwapRouter.json",
  MockRebasingLST: "MockRebasingLST.sol/MockRebasingLST.json",
};

mkdirSync(dest, { recursive: true });

const bundle = {};
for (const [name, path] of Object.entries(WANTED)) {
  try {
    const artifact = JSON.parse(readFileSync(resolve(out, path), "utf8"));
    bundle[name] = artifact.abi;
    console.log(`  ${name}: ${artifact.abi.length} entries`);
  } catch {
    console.error(`  MISSING ${name} — run \`forge build\` in contracts/ first`);
    process.exit(1);
  }
}

writeFileSync(
  resolve(dest, "abis.ts"),
  `// GENERATED by scripts/extract-abis.mjs — do not edit by hand.\n` +
    Object.entries(bundle)
      .map(([n, abi]) => `export const ${n}Abi = ${JSON.stringify(abi)} as const;`)
      .join("\n\n") +
    "\n",
);

console.log("wrote src/generated/abis.ts");
